services:
  - type: web
    name: atmostrace
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: NASA_API_URL
        value: https://ssd-api.jpl.nasa.gov/fireball.api?limit=20 